# Socket

In [ ]:
import streampu as spu
import numpy as np

## Python interface

In [20]:
x = spu.array([1,2,3,4])
print(x)

[[1 2 3 4]]


## NumPy interface
### From NumPy to StreamPu

In [40]:
l = np.array([1,2,3,4], np.float32)
x = spu.array(l)
print("A", x.dtype, "socket containing the data", x)
print(repr(x))

A float32 socket containing the data [[1. 2. 3. 4.]]
socket([[1. 2. 3. 4.]], dtype=float32, name=data, task=Array.read)


In [32]:
l[2] = 1
x

socket([[1. 2. 1. 4.]], dtype=float32, name=data, task=Array.read)

### From StreamPu to Numpy

In [42]:
src = spu.source_random(8, dtype = spu.int64)
x,_ = src.generate()
px = x.numpy
print(px)

[[0 1 1 0 1 1 1 1]]


In [29]:
src.generate.exec()
x

array([[0, 1, 1, 0, 1, 1, 1, 1]], dtype=int64)